CIS/Models/Contract.cs
using CIS._UtilClasses;
using PMSRedirect;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace CIS.Models
{
    public class Contract
    {
        #region Fields
        [Required]
        public int? ID { get; set; }

        [Display(Name = "Contract No.")]
        public string ContractNo { get; set; } = null;

        [Display(Name = "Holder ID")]
        public int? HolderID { get; set; }

        [Display(Name = "Holder Type")]
        public int? HolderType { get; set; }

        public string Status { get; set; } = null;

        [Display(Name = "Start Date")]
        public DateTime? StartDate { get; set; }

        [Display(Name = "End Date")]
        public DateTime? EndDate { get; set; }

        [Display(Name = "Description")]
        public string Contract_Description { get; set; } = null;

        [Display(Name = "Status")]
        public string Contract_Status { get; set; } = null;

        [Display(Name = "Offer")]
        public string Contract_Offer { get; set; } = null;

        [Display(Name = "Encoded By")]
        public int? EncBy { get; set; }

        [Display(Name = "Date Encoded")]
        public DateTime? EncDate { get; set; }

        [Display(Name = "Modified By")]
        public int? ModifiedBy { get; set; }

        [Display(Name = "Date Modified")]
        public DateTime? ModifiedDate { get; set; }
        #endregion Fields

        UserSessions session = new UserSessions();
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["Contact"].ConnectionString);

        #region Select
        public List<Contract> Select()
        {
            DBObject dbObj = new DBObject();
            DataTable dt = dbObj.Query(
                "Contact",
                "SELECT * from tbl_Contracts",
                new Dictionary<string, object>()
            );

            List<Contract> contracts = new List<Contract>();

            foreach (DataRow r in dt.Rows)
            {
                contracts.Add(
                    new Contract()
                    {
                        ID = r.IsNull("ID") ? default(int) : Convert.ToInt32(r["ID"]),
                        HolderID = r.IsNull("HolderID") ? default(int) : Convert.ToInt32(r["HolderID"]),
                        HolderType = r.IsNull("HolderType") ? default(int) : Convert.ToInt32(r["HolderType"]),
                        Status = r.IsNull("Status") ? default(string) : Convert.ToString(r["Status"]),
                        StartDate = r.IsNull("StartDate") ? default(DateTime) : Convert.ToDateTime(r["StartDate"]),
                        EndDate = r.IsNull("EndDate") ? default(DateTime) : Convert.ToDateTime(r["EndDate"]),

                        EncBy = r.IsNull("EncBy") ? default(int) : Convert.ToInt32(r["EncBy"]),
                        EncDate = r.IsNull("EncDate") ? default(DateTime) : Convert.ToDateTime(r["EncDate"]),
                        ModifiedBy = r.IsNull("ModifiedBy") ? default(int) : Convert.ToInt32(r["ModifiedBy"]),
                        ModifiedDate = r.IsNull("ModifiedDate") ? default(DateTime) : Convert.ToDateTime(r["ModifiedDate"]),
                    }
                );
            }

            return contracts;

        }

        #endregion Select

        #region Insert
        public void Insert(Contract contract)
        {
            //try
            {
                DBObject dbObj = new DBObject();
                DataTable dt = dbObj.Query(
                    "Contact",
                    "INSERT INTO tbl_Contracts (HolderID, HolderType, Status, StartDate, EndDate, EncBy, ModifiedBy) " +
                    "VALUES (@HolderID, @HolderType, @Status, @StartDate, @EndDate, @EncBy, @ModifiedBy)",
                    new Dictionary<string, object> {
                        {"@HolderID", contract.HolderID},
                        {"@HolderType", contract.HolderType },
                        {"@Status", contract.Status },
                        {"@StartDate", contract.StartDate },
                        {"@EndDate", contract.ID },

                        {"@EncBy", session.User.ID },
                        { "@ModifiedBy", session.User.ID }
                    }
                );
            }
            //catch (Exception e)
            //{
            //    throw e;
            //}
        }
        #endregion Insert

        #region Update
        public void Update(Contract contract)
        {
            try
            {
                DBObject dbObj = new DBObject();
                DataTable dt = dbObj.Query(
                    "Contact",
                    "UPDATE tbl_Contracts SET " +
                    "HolderID = @HolderID, HolderType = @HolderType, Status = @Status, StartDate = @StartDate, EndDate = @EndDate, ModifiedBy = @ModifiedBy, ModifiedDate = @ModifiedDate ",
                    new Dictionary<string, object> {
                        {"@HolderID", contract.HolderID},
                        {"@HolderType", contract.HolderType },
                        {"@Status", contract.Status },
                        {"@StartDate", contract.StartDate },
                        {"@EndDate", contract.ID },

                        { "@ModifiedBy", session.User.ID },
                        { "@ModifiedDate", DateTime.Now }
                    }
                );
            }
            catch (Exception e)
            {
                throw e;
            }
        }
        #endregion Update

        #region Delete
        public void Delete(int? ID)
        {
            //try
            {
                DBObject dbObj = new DBObject();
                DataTable dt = dbObj.Query(
                    "Contact",
                    "DELETE FROM tbl_Contracts WHERE ID = @ID",
                    new Dictionary<string, object> { { "@ID", ID } }
                );
            }
            //catch (Exception e)
            //{
            //    throw e;
            //}
        }
        #endregion Delet

        #region Details
        public Contract Details(int? searchID = null)
        {
            DBObject dbObj = new DBObject();
            DataTable dt = dbObj.Query(
                "Contact",
                $"SELECT * from tbl_Contracts " + ((searchID == null) ? "" :
                $"WHERE ID = {searchID}"),
                new Dictionary<string, object>()
            );

            Contract contract = new Contract();
            foreach (DataRow r in dt.Rows)
            {
                if (r != null)
                {
                    contract = new Contract()
                    {
                        ID = r.IsNull("ID") ? default(int) : Convert.ToInt32(r["ID"]),
                        HolderID = r.IsNull("HolderID") ? default(int) : Convert.ToInt32(r["HolderID"]),
                        HolderType = r.IsNull("HolderType") ? default(int) : Convert.ToInt32(r["HolderType"]),
                        Status = r.IsNull("Status") ? default(string) : Convert.ToString(r["Status"]),
                        StartDate = r.IsNull("StartDate") ? default(DateTime) : Convert.ToDateTime(r["StartDate"]),
                        EndDate = r.IsNull("EndDate") ? default(DateTime) : Convert.ToDateTime(r["EndDate"]),

                        EncBy = Convert.ToInt32(r["EncBy"]),
                        EncDate = Convert.ToDateTime(r["EncDate"]),
                        ModifiedBy = Convert.ToInt32(r["ModifiedBy"]),
                        ModifiedDate = Convert.ToDateTime(r["ModifiedDate"]),
                    };
                }
            }

            return contract;

        }
        #endregion Details
    }
}

CIS/Controllers/ContractController.cs
using CIS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CIS.Controllers
{
    public class ContractController : Controller
    {
        #region Select
        [HttpGet]
        public ActionResult Select()
        {
            Contract contract = new Contract();
            return PartialView("Select", contract.Select());
        }
        #endregion Select

        #region Insert
        [HttpGet]
        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insert(Contract contract)
        {
            contract.Insert(contract);
            return RedirectToAction("Select");
        }
        #endregion Insert

        #region Update
        [HttpGet]
        public ActionResult Update(int ID)
        {
            Contract contract = new Contract();
            return PartialView("Update", contract.Details(ID));
        }

        [HttpPost]
        public ActionResult Update(Contract contract)
        {
            contract.Update(contract);
            return RedirectToAction("Select");
        }
        #endregion Update

        #region Delete
        [HttpGet]
        public ActionResult Delete(int ID)
        {
            Contract contract = new Contract();
            return PartialView("Delete", contract.Details(ID));
        }

        [HttpPost]
        public ActionResult Delete(Contract contract)
        {
            contract.Delete(contract.ID);
            return RedirectToAction("Select");
        }
        #endregion Delete

        #region Details
        [HttpGet]
        public ActionResult Details(int ID)
        {
            Contract contract = new Contract();
            return PartialView(contract.Details(ID));
        }
        #endregion Details
    }
}

CIS/Views/Contract/Delete.cshtml
@model CIS.Models.Contract

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h6 class="card-title">Delete</h6>
            </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row mb-2 g-2">
                        <div class="col-md-6">
                            @Html.LabelFor(model => Model.ID, htmlAttributes: new { @class = "form-label" })
                            @Html.DropDownListFor(model => Model.ID, new CIS.Models.Contact().ListEmployee(), "Select Employee", new { @class = "form-select" })
                            @Html.ValidationMessageFor(model => Model.ID, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.EncBy, htmlAttributes: new { @class = "form-label" })
                            @Html.EditorFor(model => model.EncBy, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EncBy, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.EncDate, htmlAttributes: new { @class = "form-label" })
                            @Html.DropDownListFor(model => model.EncDate, new CIS.Models.NetworkType().NetworkTypes(), "Select Network", new { @class = "form-select" })
                            @Html.ValidationMessageFor(model => model.EncDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.HolderID, htmlAttributes: new { @class = "form-label" })
                            @Html.EditorFor(model => model.HolderID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HolderID, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.HolderType, htmlAttributes: new { @class = "form-label" })
                            @Html.TextAreaFor(model => model.HolderType, 10, 5, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.HolderType, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-12">
                            <input type="submit" name="name" value="Delete" class="btn btn-danger" />
                            @Html.ActionLink("Back to List", "Select", "Contract", "", new { @class = "btn btn-secondary" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

CIS/Views/Contract/Details.cshtml
@model CIS.Models.Contract

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div class="row mb-3">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h6 class="card-title">Profile</h6>
            </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row mb-2 g-2">
                        <div class="col-md-12">
                            <div class="form-label">HolderID</div>
                            <div class="row form-control" style="--bs-gutter-x: 0">@Model.HolderID </div>
                        </div>
                        <div class="col-md-12">
                            <label>HolderType</label>
                            <div class="row form-control" style="--bs-gutter-x: 0">@Model.HolderType</div>
                        </div>

                        <div class="col-md-12">
                            @Html.ActionLink("Back to List", "Select", "Contract", "", new { @class = "btn btn-secondary" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    
</div>

CIS/Views/Contract/Insert.cshtml
@model CIS.Models.Contract

<h1>Insert</h1>

<div class="row">
    <div class="col-md-6 m-auto">
        <div class="card">
            <div class="card-header">
                <h6 class="card-title">Register Contract</h6>
            </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row mb-2 g-2">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.HolderType, htmlAttributes: new { @class = "form-label" })
                            @Html.EditorFor(model => model.HolderType, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HolderType, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-12">
                            <input type="submit" name="name" value="Create" class="btn btn-primary" />
                            @Html.ActionLink("Back to List", "Select", "Contract", "", new { @class = "btn btn-secondary" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

CIS/Views/Contract/Select.cshtml
@model IEnumerable<CIS.Models.Contract>

@{
    ViewBag.Title = "Select";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="tableDiv">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h6 style="display:inline-block;">Contract</h6>
                @Html.ActionLink("Create New", "Insert", "", new { @class = "btn btn-primary text-white", style = "display:inline-block; float:right" })
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="data" class="table table-hover table-striped">
                    <thead class="table-dark">
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.ID)</th>
                            <th>@Html.DisplayNameFor(model => model.HolderID)</th>
                            <th>@Html.DisplayNameFor(model => model.HolderType)</th>
                            <th>@Html.DisplayNameFor(model => model.Status)</th>
                            <th>@Html.DisplayNameFor(model => model.StartDate)</th>
                            <th>@Html.DisplayNameFor(model => model.EndDate)</th>
                            <th>@Html.DisplayNameFor(model => model.EncBy)</th>
                            <th>@Html.DisplayNameFor(model => model.EncDate)</th>
                            <th>@Html.DisplayNameFor(model => model.ModifiedBy)</th>
                            <th>@Html.DisplayNameFor(model => model.ModifiedDate)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.ID </td>
                                <td>@item.HolderID </td>
                                <td>@item.HolderType </td>
                                <td>@item.Status </td>
                                <td>@item.StartDate </td>
                                <td>@item.EndDate </td>
                                <td>@item.EncBy </td>
                                <td>@item.EncDate</td>
                                <td>@item.ModifiedBy</td>
                                <td>@item.ModifiedDate</td>
                                <td>
                                    <div class="text-center">
                                        <div class="btn-group">
                                            <a href="@Url.Action("Update","Contract", new { id=item.ID})" class="btn btn-secondary btn-sm" title="Edit"><i class="fa-solid fa-pen-to-square"></i></a>
                                            <a href="@Url.Action("Details","Contract", new { id=item.ID })" class="btn btn-secondary btn-sm" title="Details"><i class="fa-solid fa-circle-info"></i></a>
                                            <a href="@Url.Action("Delete","Contract", new { id=item.ID})" class="btn btn-secondary btn-sm" title="Delete"><i class="fa-solid fa-trash"></i></a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>




<script>
    $("#data").DataTable();
</script>


@section scripts{
    <script>
        LoadData("");
        $('#searchItem').on('keyup', function () {
            var searchItem = $(this).val();
            LoadData(searchItem);
        });

        $("#data").DataTable();

        function LoadData(search)
        {
            $.ajax({
                url: '@Url.Action("Select", "Contract")',
                type: 'GET'
            });
        }
    </script>
}

CIS/Views/Contract/Update.cshtml
@model CIS.Models.Contract

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update</h1>

<div style="margin:auto">
    <div class="row">
        <div class="col-md-8 m-auto">
            <div class="card">
                <div class="card-header">
                    <h6 class="card-title">Edit</h6>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row mb-2 g-2">
                            <div class="col-md-6">
                                @Html.LabelFor(model => Model.HolderID, htmlAttributes: new { @class = "form-label" })
                                @Html.DropDownListFor(model => Model.HolderID, new CIS.Models.Contact().ListEmployee(), "Select Employee", new { @class = "form-select mb-2" })
                                @Html.ValidationMessageFor(model => Model.HolderID, "", new { @class = "text-danger" })
                            </div>
                            
                            <div class="col-md-12">
                                <input type="submit" name="name" value="Save" class="btn btn-primary" />
                                @Html.ActionLink("Back to List", "Select", "Contract", "", new { @class = "btn btn-secondary" })
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>