MobilePlan/Controllers/NetworkTypeController.cs
using Microsoft.Reporting.WebForms;
using MobilePlan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobilePlan.Controllers
{
    public class NetworkTypeController : Controller
    {
        // GET: NetworkType
        NetworkType mod = new NetworkType();
        public ActionResult Index(string Search = "")
        {
            var list = mod.List(Search);
            return View(list);
        }

        public ActionResult Action(string Type, int? ID = null)
        {
            switch (Type)
            {
                case "Detail":
                    return RedirectToAction("Detail", new { ID = ID });
                case "Add":
                    return RedirectToAction("Create");
                case "Edit":
                    return RedirectToAction("Edit", new { ID = ID });
                case "Delete":
                    return RedirectToAction("Delete", new { ID = ID });
                case "ItemView":
                    return RedirectToAction("ItemView", new { ID = ID });
            }
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(NetworkType m)
        {
            if (ModelState.IsValid)
            {
                if (mod.Create(m) != 0)
                {
                    ViewBag.Message = "Data successfully created!";
                }
                else
                {
                    ModelState.AddModelError("", "Data has duplicate value!");
                }
            }

            ViewBag.Execute = "ReloadPage()";
            return PartialView("Field", m);
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            var item = mod.Find(ID);
            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(NetworkType m)
        {
            if (ModelState.IsValid)
            {
                mod.Update(m);
                ViewBag.Message = "Data successfully saved!";
                ViewBag.Execute = "ReloadPage()";
            }
            return PartialView("Field", m);
        }
        
        public ActionResult Detail(int ID)
        {
            var item = mod.Find(ID);
            return View(item);
        }
        
        public ActionResult Delete(int ID)
        {
            var item = mod.Find(ID);
            return View(item);
        }

        [HttpPost]
        public ActionResult Delete(NetworkType m)
        {
            if (ModelState.IsValid)
            {
                mod.Delete(m);
                ViewBag.Message = "Data successfully saved!";
                ViewBag.Execute = "ReloadPage()";
            }
            return PartialView("Field", m);
        }


        [HttpGet]
        public ActionResult ItemView(int ID)
        {
            var item = mod.Find(ID);
            return PartialView(item);
        }

        [HttpGet]
        public ActionResult Report(int ID)
        {
            //var item = mod.Find(ID);
            return PartialView();
        }

        public ActionResult Print(DateTime? StartDate, DateTime? EndDate, int ID = 0, int Status = 0, Format Format = Format.PDF)
        {
            //if (StartDate == null)
            //{
            //    StartDate = DateTime.Parse("1753-01-01 00:00:00.000");
            //}
            //if (EndDate == null)
            //{
            //    EndDate = DateTime.Parse("1753-01-01 00:00:00.000");
            //}
            ReportViewer rv = new ReportViewer(); //EXCELOPENXML FOR EXCEL & application/vnd.ms-excel FOR contentType
            rv.LocalReport.ReportPath = Server.MapPath("~/Reports/Report1.rdlc");
            rv.LocalReport.Refresh();

            var item = new Contact().List(StartDate, EndDate, ID, ( (Status==0) ? "All" : ((Status==1) ? "Active" : "Terminated")) );
            rv.LocalReport.DataSources.Add(new ReportDataSource("ds_Network", item));
            //Microsoft.Reporting.WebForms.ReportViewer.LocalReport
            //rv.LocalReport.DataSources.Add(new ReportDataSource("DataSet1", new NetworkType().List()));

            var file = rv.LocalReport.Render(Format == Format.PDF ? "pdf" : "EXCELOPENXML");
            
            Response.ContentType = Format == Format.PDF ? "application/pdf" : "application/vnd.ms-excel";
            Response.AddHeader("content-disposition", Format == Format.PDF ? $"inline;filename=MPReport {DateTime.Now:yyyyMMddhhmmss}.pdf" : $"inline;filename=ITSD {DateTime.Now:yyyyMMddhhmmss}.xlsx");
            Response.Buffer = true;
            Response.Clear();
            Response.BinaryWrite(file);
            Response.End();
            return View(file);
        }

        public enum Format
        {
            PDF,
            Excel
        }
    }
}

MobilePlan/Views/NetworkType/Create.cshtml
@model MobilePlan.Models.NetworkType

@{
    ViewBag.Title = "New";
    Layout = null;
}

@using (Ajax.BeginForm("Create", new AjaxOptions { UpdateTargetId = "fielddata" }))
{
    <div class="modal-header bg-primary text-white">
        <h6>@ViewBag.Title</h6>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <div id="fielddata" class="row mb-2 g-2">
            @Html.Partial("Field")
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" value="Create" class="btn btn-success text-white" />
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

MobilePlan/Views/NetworkType/Delete.cshtml
@model MobilePlan.Models.NetworkType

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

@using (Ajax.BeginForm("Delete", new AjaxOptions { UpdateTargetId = "fielddata" }))
{
    <div class="modal-header bg-danger text-white">
        <h6>@ViewBag.Title</h6>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        @Html.HiddenFor(f => f.ID)
        <div id="fielddata" class="row mb-2 g-2">
            @Html.Partial("Field")
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" value="Delete" class="btn btn-danger text-white" />
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
    </div>
}



@Scripts.Render("~/bundles/jqueryval")

MobilePlan/Views/NetworkType/Detail.cshtml
@model MobilePlan.Models.NetworkType

@{
    ViewBag.Title = "Details";
    Layout = null;
}

@using (Ajax.BeginForm("Detail", new AjaxOptions { UpdateTargetId = "fielddata" }))
{
    <div class="modal-header">
        <h6>@ViewBag.Title</h6>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        @Html.HiddenFor(f => f.ID)
        <div id="fielddata" class="row mb-2 g-2">
            @Html.Partial("Field")
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" value="Prev" class="btn text-white" />
        <input type="submit" value="Next" class="btn text-white" />
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
    </div>
}



@Scripts.Render("~/bundles/jqueryval")

MobilePlan/Views/NetworkType/Edit.cshtml
@model MobilePlan.Models.NetworkType

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

@using (Ajax.BeginForm("Edit", new AjaxOptions { UpdateTargetId = "fielddata" }))
{
    <div class="modal-header bg-success text-white">
        <h6>@ViewBag.Title</h6>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        @Html.HiddenFor(f => f.ID)
        <div id="fielddata" class="row mb-2 g-2">
            @Html.Partial("Field")
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" value="Save" class="btn btn-success text-white" />
        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

MobilePlan/Views/NetworkType/Field.bak.cshtml
@model MobilePlan.Models.NetworkType
@{ 
    
}
<div class="col-md-12">
	@if(ViewBag.Message != null)
	{
		<p class="alert alert-success">@ViewBag.Message</p>
	}
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>
<div class="col-md-12">
@Html.LabelFor(model => model.Network)
@Html.EditorFor(model => model.Network, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
@Html.ValidationMessageFor(model => model.Network, "", new { @class = "text-danger" })
</div>

<script>
    @ViewBag.Execute
</script>

MobilePlan/Views/NetworkType/Field.cshtml
@model MobilePlan.Models.NetworkType
@{ 
    
}
<div class="col-md-12">
	@if(ViewBag.Message != null)
	{
		<p class="alert alert-success">@ViewBag.Message</p>
	}
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>
<div class="col-md-12">
@Html.LabelFor(model => model.Network)
@Html.EditorFor(model => model.Network, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
@Html.ValidationMessageFor(model => model.Network, "", new { @class = "text-danger" })
</div>

<script>
    @ViewBag.Execute
</script>

MobilePlan/Views/NetworkType/Index.bak.cshtml
@model IEnumerable<MobilePlan.Models.NetworkType>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Execute = "location.reload()";
}




<div class="card">
    <div class="card-header">
        <h6>@ViewBag.Title</h6>
    </div>
    <div class="card-body">
        <div class="row row-cols-lg-auto g-1 align-items-center">
            <div class="col">
                <p>
					<a href="#" class="btn btn-sm btn-success"><i class="fa fa-plus-square"></i>&nbsp;Create</a>
                </p>
            </div>
        </div>
        <div class="table-responsive">
            <table id="data" class="table table-hover table-striped" style="font-size:0.9rem;">
                <thead class="table-dark">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Network)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Network)</td>
                            <td class="text-nowrap">
                                <a href="#" class="text-dark" title="Edit/Modify" onclick="Actions('Edit', @item.ID)"><i class="fa fa-edit"></i></a> &nbsp;
                                <a href="#" class="text-dark" title="Details" onclick="Actions('Detail', @item.ID)"><i class="fa fa-sticky-note "></i></a> &nbsp;
                                <a href="#" class="text-dark" title="Delete" onclick="Actions('Delete', @item.ID)"><i class="fa fa-trash"></i></a> &nbsp;
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@foreach (var item in Model)
{
    if (item.ID >0  )
    {
        <div class="card">
            <div class="card-header">
                <h6>@item.Network.ToUpper() Network Users</h6>
            </div>
            <div class="card-body">
                <div class="row row-cols-lg-auto g-1 align-items-center">
                    <div class="col">
                        @*<p>
                            <a href="#" onclick="Actions('Add')" class="btn btn-sm btn-success"><i class="fa fa-plus-square"></i>&nbsp;Create</a>
                        </p>*@
                    </div>
                </div>
                <div class="table-responsive">
                    <table id="" class="table network-table table-hover table-striped" style="font-size:0.9rem;">
                        <thead class="table-dark">
                            <tr>
                                @*<th>@Html.DisplayNameFor(model => model.Network)</th>*@
                                <th>End-User</th>
                                <th>Phone Number</th>
                                <th>Network</th>
                                <th>BINCARD</th>
                                <th>Remarks</th>

                                <th>Contract Start Date</th>
                                <th>Contract End</th>
                                <th>Status</th>
                                <th>Overdue Balance</th>
                                <th>Early Renewal Fee</th>

                                <th>Exisitng Plan</th>
                                <th>Inclusion</th>
                                <th>Handset Model</th>
                                <th>Existing Duo No.</th>
                                <th>Credit Limit</th>

                                <th>Spending Limit</th>
                                <th>Billing Cycle</th>
                                @*<th></th>*@
                                @*<th></th>*@
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var inneritem in MobilePlan.Models.NetworkType.NetworkContactList(item.ID) )
                            {
                                <tr>
                                    @*<td>@Html.DisplayFor(modelItem => item.Network )</td>*@
                                
                                    <td>@inneritem.EndUserName </td>
                                    <td>@inneritem.MobileNo</td>
                                    <td>@inneritem.NetworkTypeName</td>
                                    <td>@inneritem.BINCARD</td>
                                    <td>@inneritem.Remarks</td>

                                    <td>@inneritem.ContractStart</td>
                                    <td>@inneritem.ContractEnd</td>
                                    <td>@inneritem.Status</td>
                                    <td>@inneritem.OverdueBalance</td>
                                    <td>@inneritem.EarlyRenewal</td>

                                    <td>@inneritem.ExistingPlan</td>
                                    <td>@inneritem.Inclusion</td>
                                    <td>@inneritem.HandsetModel</td>
                                    <td>@inneritem.ExistingDuoNo</td>
                                    <td>@inneritem.CreditLimit</td>

                                    <td>@inneritem.SpendingLimit</td>
                                    <td>@inneritem.BillingCycle</td>
                                    @*<td class="text-nowrap">
                                        @*<a href="#" class="text-dark" title="Edit/Modify" onclick="Actions('Edit', @item.ID)"><i class="fa fa-edit"></i></a> &nbsp;
                                        <a href="#" class="text-dark" title="Details" onclick="Actions('Detail', @item.ID)"><i class="fa fa-sticky-note "></i></a> &nbsp;
                                        <a href="#" class="text-dark" title="Delete" onclick="Actions('Delete', @item.ID)"><i class="fa fa-trash"></i></a> &nbsp;
                                        @*<a href="" class="text-dark" title="Edit/Modify" onclick="ActionsContact('Edit', @item.ID)"><i class="fa fa-edit"></i></a> &nbsp;
                                        <a href="" class="text-dark" title="Details" onclick="ActionsContact('Detail', @item.ID)"><i class="fa fa-sticky-note "></i></a> &nbsp;
                                        <a href="" class="text-dark" title="Delete" onclick="ActionsContact('Delete', @item.ID)"><i class="fa fa-trash"></i></a> &nbsp;
                                    </td>*@
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }
}

<!-- Modal -->
<div class="modal fade" id="ModalEntry" data-bs-backdrop="static">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div id="modalcontent" class="modal-content">

        </div>
    </div>
</div>


@section scripts {
    <script>
        $('#data').DataTable({
            ordering: true,
            searching: true
        });

        //$('#data-sub').DataTable({
        //    ordering: false,
        //    searching: true
        //});

        $('.network-table').DataTable({
            ordering: false,
            searching: true
        });

		$('#ModalEntry').draggable();

		function Actions(Type, ID) {
			Ajax('@Url.Action("Action")', {Type : Type ,ID : ID}, 'html', function(data) {
				$('#modalcontent').html(data);
				$('#ModalEntry').modal('show');
			});
		}

        function ActionsContact(Type, ID) {
            Ajax('@Url.Action("Action", "Contact")', { Type: Type, ID: ID }, 'html', function (data) {
                $('#modalcontent').html(data);
                $('#ModalEntry').modal('show');
            });
        }

        function ReloadPage() {
            location.reload();
        }
    </script>
}

MobilePlan/Views/NetworkType/Index.cshtml
@model IEnumerable<MobilePlan.Models.NetworkType>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Execute = "location.reload()";
}


<div class="card">
    <div class="card-header">
        <h6>Mobile Network Providers</h6>
    </div>
    <div class="card-body">
        <div class="row row-cols-lg-auto g-1 align-items-center">
            <div class="col">
                <p>
					<a href="#" onclick="Actions('Add')" class="btn btn-sm btn-success"><i class="fa fa-plus-square"></i>&nbsp;Create</a>
                </p>
            </div>
        </div>
        <div class="table-responsive">
            <table id="data" class="table table-hover table-striped" style="font-size:0.9rem;">
                <thead class="table-dark">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Network)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (item.ID != 0)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Network)</td>
                                <td class="text-nowrap">
                                    <a href="#" class="text-dark" title="Edit/Modify" onclick="Actions('Edit', @item.ID)"><i class="fa fa-edit"></i></a> &nbsp;
                                    <a href="#" class="text-dark" title="Details" onclick="Actions('Detail', @item.ID)"><i class="fa fa-sticky-note "></i></a> &nbsp;
                                    <a href="#" class="text-dark" title="Delete" onclick="Actions('Delete', @item.ID)"><i class="fa fa-trash"></i></a> &nbsp;
                                </td>
                            </tr>
                        }

                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@foreach (var item in Model)
{
    if (item.ID != 0)
    {
        <div class="card">
            <div class="card-header">
                <h6>@item.Network.ToUpper() Network Users</h6>
            </div>
            <div class="card-body">
                <div class="row row-cols-lg-auto g-1 align-items-center">
                    <div class="col">
                        @*<p>
                                <a href="#" onclick="Actions('Add')" class="btn btn-sm btn-success"><i class="fa fa-plus-square"></i>&nbsp;Create</a>
                            </p>*@
                    </div>
                </div>
                <div class="table-responsive">
                    <table id="" class="table network-table table-hover table-striped" style="font-size:0.9rem;">
                        <thead class="table-dark">
                            <tr>
                                @*<th>@Html.DisplayNameFor(model => model.Network)</th>*@
                                <th>End-User</th>
                                <th>Mobile Number</th>
                                <th>Network</th>
                                <th>BINCARD</th>
                                <th>Status</th>
                                <th>Existing Plan</th>
                                @*<th>Account Name</th>
                                <th>Account No</th>
                                <th>Contract Start Date</th>
                                <th>Contract End Date</th>
                                <th>Inclusion</th>
                                <th>Handset Model</th>
                                <th>Existing Duo No.</th>
                                <th>Credit Limit</th>
                                <th>Spending Limit</th>
                                <th>Billing Cycle</th>
                                <th>Remarks</th>*@
                                @*<th>Overdue Balance</th>
                                    <th>Early Renewal Fee</th>*@
                                @*<th></th>*@
                                @*<th></th>*@
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var inneritem in MobilePlan.Models.NetworkType.NetworkContactList(item.Network))
                            {
                                <tr>
                                    @*<td>@Html.DisplayFor(modelItem => item.Network )</td>*@
                                    <td>@inneritem.EndUserName </td>
                                    <td>@inneritem.MobileNo</td>
                                    <td>@inneritem.NetworkTypeName</td>
                                    <td>@inneritem.BINCARD</td>
                                    <td>@inneritem.Status</td>
                                    <td>@inneritem.ExistingPlan</td>
                                    @*<td>@inneritem.AccountName </td>
                                    <td>@inneritem.AccountNo </td>
                                    <td>@inneritem.ContractStart</td>
                                    <td>@inneritem.ContractEnd</td>
                                    <td>@inneritem.Inclusion</td>
                                    <td>@inneritem.HandsetModel</td>
                                    <td>@inneritem.ExistingDuoNo</td>
                                    <td>@inneritem.CreditLimit</td>
                                    <td>@inneritem.SpendingLimit</td>
                                    <td>@inneritem.BillingCycle</td>
                                    <td>@inneritem.Remarks</td>*@
                                    @*<td>@inneritem.OverdueBalance</td>
                                        <td>@inneritem.EarlyRenewal</td>*@
                                    @*<td class="text-nowrap">
                                            @*<a href="#" class="text-dark" title="Edit/Modify" onclick="Actions('Edit', @item.ID)"><i class="fa fa-edit"></i></a> &nbsp;
                                            <a href="#" class="text-dark" title="Details" onclick="Actions('Detail', @item.ID)"><i class="fa fa-sticky-note "></i></a> &nbsp;
                                            <a href="#" class="text-dark" title="Delete" onclick="Actions('Delete', @item.ID)"><i class="fa fa-trash"></i></a> &nbsp;
                                            @*<a href="" class="text-dark" title="Edit/Modify" onclick="ActionsContact('Edit', @item.ID)"><i class="fa fa-edit"></i></a> &nbsp;
                                            <a href="" class="text-dark" title="Details" onclick="ActionsContact('Detail', @item.ID)"><i class="fa fa-sticky-note "></i></a> &nbsp;
                                            <a href="" class="text-dark" title="Delete" onclick="ActionsContact('Delete', @item.ID)"><i class="fa fa-trash"></i></a> &nbsp;
                                        </td>*@
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }

}

<!-- Modal -->
<div class="modal fade" id="ModalEntry" data-bs-backdrop="static">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div id="modalcontent" class="modal-content">

        </div>
    </div>
</div>


@section scripts {
    <script>
        $('#data').DataTable({
            ordering: true,
            searching: true
        });

        //$('#data-sub').DataTable({
        //    ordering: false,
        //    searching: true
        //});

        $('.network-table').DataTable({
            ordering: false,
            searching: true
        });

		$('#ModalEntry').draggable();

		function Actions(Type, ID) {
			Ajax('@Url.Action("Action")', {Type : Type ,ID : ID}, 'html', function(data) {
				$('#modalcontent').html(data);
				$('#ModalEntry').modal('show');
			});
		}

        function ActionsContact(Type, ID) {
            Ajax('@Url.Action("Action", "Contact")', { Type: Type, ID: ID }, 'html', function (data) {
                $('#modalcontent').html(data);
                $('#ModalEntry').modal('show');
            });
        }

        function ReloadPage() {
            location.reload();
        }
    </script>
}

MobilePlan/Views/NetworkType/Report.cshtml
@model MobilePlan.Models.NetworkType
<div class="modal fade" id="ReportModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            @using (Html.BeginForm("Print", "NetworkType", FormMethod.Post, new { target = "_blank" }))
            {
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Filter Report</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-2 g-1">
                        <div class="col-md-6">
                            Starting Date
                            <input type="date" name="StartDate" class="form-control" value="" />
                        </div>
                        <div class="col-md-6">
                            End Date
                            <input type="date" name="EndDate" class="form-control" value="" />
                        </div>
                        
                        <div class="col-md-12">
                            Status
                            <select class="form-select" name="Status">
                                <option value="0">All</option>
                                <option value="1">Active</option>
                                <option value="2">Terminated</option>
                            </select>
                        </div>
                        <div class="col-md-12">
                            Network Provider
                            @Html.DropDownListFor(model => model.ID, new MobilePlan.Models.NetworkType().ListNetwork(), new { @class = "form-select form-select-sm network-provider" })
                        </div>
                        <div class="col-md-12">
                            FORMAT
                            <select class="form-select" name="Format">
                                <option value="0">PDF</option>
                                <option value="1">Excel</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Generate Report</button>
                </div>
            }
        </div>
    </div>
</div>